name: Pull Request
on:
  push:
    branches-ignore:
       - master

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
       - name: check out the repository
         uses: actions/checkout@v4

       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v5